version: "3"
services:
  api:
    build: .
    image: spa_react_typescript_hello-world_starter
    container_name: spa_react_typescript_hello-world_starter
    ports:
      - "4040:80"
    env_file:
      - .env
